# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6e9cba065724b953106ae21976f233b469c6b8f8c9d02c591c4b7e6bc294827232a88323f50670d68938ceb38255c20e484c58b46c5ea629038db646191c290

test:
  secret_key_base: 842adbbe9c61bc3ab5fb118b37f8f2cff70419cd09fd1fecd2a7a7a523e32adcda01daecd962d45b33d982c99c01b2d8d30ba5b8a431cf21dc4a1595969d53b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
